version: '3.7'

services:
  db:
    image: mysql:8
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: ecommerce 
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
